source 'https://rubygems.org'
ruby '2.1.1'

gem 'rails', '4.1.0'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails', "~> 2.3.0" 
gem 'jquery-ui-rails'
gem 'rails4-autocomplete'
gem 'bootstrap-sass'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0'
gem 'spring'
gem 'pg'
gem 'sprockets'
gem 'railties'
