development:
  adapter: postgresql
  encoding: unicode
  database: college_cost_development
  pool: 5
  username: qf
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: college_cost_test
  pool: 5
  username: qf
  password: